# Generated by Django 4.1.10 on 2023-11-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("printingRestFullAPI", "0011_automationstatus"),
    ]

    operations = [
        migrations.CreateModel(
            name="PrintingHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("googleId", models.CharField(max_length=250)),
                ("print_date", models.DateTimeField(auto_now_add=True)),
                ("pages_printed", models.PositiveIntegerField()),
                ("document_name", models.CharField(max_length=250)),
                ("document_type", models.CharField(max_length=250)),
                ("num_pages", models.PositiveIntegerField(default=1)),
                ("is_two_sides", models.BooleanField(default=False)),
                ("department", models.CharField(default="B4", max_length=250)),
                ("floors", models.IntegerField(default=1)),
                ("printer_name", models.CharField(default="HP5000", max_length=250)),
                (
                    "page_type",
                    models.CharField(
                        choices=[("option1", "Dọc"), ("option2", "Ngang")],
                        default="option1",
                        max_length=20,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RemainingPages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("googleId", models.CharField(max_length=250)),
                ("remainder_pages", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="UserModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=250)),
                ("familyName", models.CharField(max_length=250)),
                ("givenName", models.CharField(max_length=250)),
                ("googleId", models.CharField(max_length=250)),
                ("imageUrl", models.CharField(max_length=250)),
                ("name", models.CharField(default="a", max_length=250)),
            ],
        ),
        migrations.DeleteModel(name="Automation",),
        migrations.DeleteModel(name="AutomationStatus",),
        migrations.RemoveField(model_name="controlpanel", name="author",),
        migrations.RemoveField(model_name="employee", name="author",),
        migrations.RemoveField(model_name="profile", name="user",),
        migrations.DeleteModel(name="RoomCondition",),
        migrations.DeleteModel(name="ControlPanel",),
        migrations.DeleteModel(name="Employee",),
        migrations.DeleteModel(name="Profile",),
    ]
