# Generated by Django 4.1.10 on 2023-12-03 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("printingRestFullAPI", "0013_usermodel_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermodel",
            name="name",
            field=models.CharField(default="name", max_length=250),
        ),
        migrations.CreateModel(
            name="UploadedFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fileName", models.CharField(max_length=250)),
                ("filePath", models.CharField(max_length=250)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
