# Generated by Django 4.1.10 on 2023-12-03 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("printingRestFullAPI", "0014_alter_usermodel_name_uploadedfiles"),
    ]

    operations = [
        migrations.RemoveField(model_name="uploadedfiles", name="filePath",),
    ]
