# Generated by Django 4.1.10 on 2023-12-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("printingRestFullAPI", "0015_remove_uploadedfiles_filepath"),
    ]

    operations = [
        migrations.RenameField(
            model_name="uploadedfiles", old_name="created", new_name="uploaded_at",
        ),
        migrations.AddField(
            model_name="uploadedfiles",
            name="filePath",
            field=models.FileField(default=1, upload_to="users/%Y/%m/%d/"),
            preserve_default=False,
        ),
    ]
