# Generated by Django 4.1.10 on 2023-12-03 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "printingRestFullAPI",
            "0016_rename_created_uploadedfiles_uploaded_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfiles",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="printingRestFullAPI.usermodel",
            ),
        ),
    ]
