# Generated by Django 4.1.10 on 2023-12-03 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("printingRestFullAPI", "0017_alter_uploadedfiles_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="uploadedfiles", name="user",),
        migrations.AddField(
            model_name="uploadedfiles",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="upload_table",
                to="printingRestFullAPI.usermodel",
            ),
            preserve_default=False,
        ),
    ]
