# Generated by Django 4.1.10 on 2023-12-03 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("printingRestFullAPI", "0018_remove_uploadedfiles_user_uploadedfiles_author"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="uploadedfiles", options={"ordering": ["-uploaded_at"]},
        ),
        migrations.RemoveField(model_name="uploadedfiles", name="author",),
    ]
