# Generated by Django 4.1.10 on 2023-12-03 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("printingRestFullAPI", "0019_alter_uploadedfiles_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uploadedfiles",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="upload_table",
                to="printingRestFullAPI.usermodel",
            ),
            preserve_default=False,
        ),
    ]
