# Generated by Django 4.1.10 on 2023-12-03 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("printingRestFullAPI", "0020_uploadedfiles_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="uploadedfiles",
            name="author",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="printingRestFullAPI.usermodel",
            ),
        ),
    ]
